spring:
  bootstrap:
    enabled: true
  application:
    name: hierarchy-graph-maker
  jmx:
    default-domain: ${spring.application.name}
  config:
    import: vault://,configserver:${PLATFORM_CONFIG_SERVER_URI:http://dev-config-server.foresee.com/platform-config-server}
  cloud:
    aws:
      stack:
        auto: false
    bootstrap:
      enabled: true
    vault:
      kv:
        enabled: true
        backend: cxsuite
        backendVersion: 1
        profile-separator: '/'
        default-context: common-secrets/qal
        application-name: hierarchy-graph-maker/qal
      enabled: true
      host: dev-vault.aws.foreseeresults.com
      port: 8200
      scheme: http
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
#  cloud:
#    config:
#      fail-fast: true
#      username: config-server-user
#      password: secret
#  security:
#    user:
#      name: config-server-user
#      password: secret

#    server:
#      git:
#        uri: ${PLATFORM_CONFIG_SERVER_URI:http://dev-config-server.foresee.com/platform-config-server}
#        skipSslValidation: true
#        username: config-server-user
#        password: secret
#  cloud:
#    config:
#      enabled: false
#      import-check.enabled: false

#app:
#  vault-paths:
#    - cxsuite/common-secrets/qal
#    - cxsuite/${spring.application.name}/qal

server:
  servlet:
    contextPath: /${spring.application.name}

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

## fixme
logging:
#  config: classpath:log4j2-aws.xml

  level:
    root: INFO